Vagrant.configure("2") do |config|
  config.vm.box = "ramsey/macos-mojave"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

  end
  
end
